In [2]:
import pandas as pd
import numpy as np

### Pandas Read CSV

In [3]:
df = pd.read_csv("people.csv")
df.head(5)

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

### features in pandas CSV

In [4]:
df = pd.read_csv("people.csv", usecols=["First Name","Email"])
df.head()

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

In [5]:
# setting an index column
df = pd.read_csv("people.csv", index_col="First Name")
df

,Last Name,Sex,Email,Date of birth,Job Title
First Name,,,,,
Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [6]:
# handle missing Values
df = pd.read_csv("people.csv", na_values=["N/A", "Unknown"])
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [7]:
# Reading CSV Files with Different Delimiters
# Sample data stored in a multi-line string
data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

# save data to a csv file 
with open('sample.csv', 'w') as file:
    file.write(data)

# Reading the CSV file with multiple delimiters
print(data)

totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4

In [8]:
# Load the CSV file using pandas with multiple delimiters
df = pd.read_csv('sample.csv',
                 sep='[:, |_]',  # Define the delimiters
                 engine='python')  # Use Python engine for regex separators
df

,totalbill,tip,Unnamed: 2,sex,smoker,Unnamed: 5,day,time,Unnamed: 8,size
16.99,NaN,1.01,Female,No,NaN,Sun,NaN,Dinner,NaN,2.0
10.34,NaN,1.66,NaN,Male,NaN,No,Sun,Dinner,NaN,3.0
21.01,3.50,Male,NaN,No,Sun,NaN,Dinner,NaN,3.0,NaN
23.68,NaN,3.31,NaN,Male,No,NaN,Sun,Dinner,NaN,2.0
24.59,3.61,NaN,Female,No,NaN,Sun,NaN,Dinner,NaN,4.0
25.29,NaN,4.71,Male,NaN,No,Sun,NaN,Dinner,NaN,4.0

In [9]:
# Using nrows in read_csv()
df = pd.read_csv('people.csv',nrows=5)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [10]:
#  using skiprow in csvfile
df = pd.read_csv('people.csv', skiprows=[2,5], nrows=5)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
2,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher

## writing data to csv

In [11]:
# converting to data frame
# list of name, degree, score
nme = ["aparna", "pankaj", "sudhir", "Geeku"]
deg = ["MBA", "BCA", "M.Tech", "MBA"]
scr = [90, 40, 80, 98]

# dictionary of lists
dict = {'name': nme, 'degree': deg, 'score': scr}
    
df = pd.DataFrame(dict)

In [13]:
# saving the dataframe
df.to_csv('file1.csv')
df

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [14]:
# saving without header and index
df.to_csv('file2.csv', header=False, index=False)

In [ ]:
# saving on a specific location
#  df.to_csv(r'your location path')

In [16]:
# Write a DataFrame to CSV file using Tab Separator
users = {'Name': ['Amit', 'Cody', 'Drew'],
    'Age': [20,21,25]}

#create DataFrame
df = pd.DataFrame(users, columns=['Name','Age'])

print("Original DataFrame:")
print(df)
print('Data from Users.csv:')

df.to_csv('Users.csv', sep='\t', index=False,header=True)
new_df = pd.read_csv('Users.csv')

print(new_df)

Original DataFrame:
   Name  Age
0  Amit   20
1  Cody   21
2  Drew   25
Data from Users.csv:
  Name\tAge
0  Amit\t20
1  Cody\t21
2  Drew\t25