In [44]:
import pandas as pd
import numpy as np

In [26]:
player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

In [27]:
# slicing using iloc 
df1 = df.iloc[0:4]
df1

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000

In [28]:
# slicing column in df
df1 = df.iloc[:, 0:2]
df1

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

In [29]:
# selecting the specific comlum
# iloc[Rows number , columns number]
value = df.iloc[2,3]
print("The specific cell Value is ",value)

The specific cell Value is  8428000

### Using the Boolean conditions in pandas DataFrame
 Instead of selecting rows by index we can use Boolean conditions (e.g., Age > 35) to filter rows dynamically.

In [30]:
data = df[df['Age']>35].iloc[:,:]
print("Fiiltered Data based on age >35 :\n",data)

Fiiltered Data based on age >35 :
             Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
4        C.Gayle   40     100  4528000
6     K.Peterson   42      85  2528000

### slicing using loc
Slicing Rows in Dataframe
With loc[] we can extract a range of rows by their labels instead of integer positions

In [31]:
df.set_index('Name', inplace=True)
print("DataFrame with custom index:\n",df)

DataFrame with custom index:
                Age  Weight   Salary
Name
M.S.Dhoni       36      75  5428000
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000
C.Gayle         40     100  4528000
J.Root          33      72  7028000
K.Peterson      42      85  2528000

In [32]:
custom = df.loc['A.B.D Villers':'S.Smith']
print(custom)

               Age  Weight   Salary
Name
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000

In [35]:
# selecting specific cell 
# df.loc[label, column]
values = df.loc['V.Kohli', 'Salary']
print(values)

8428000

# Filter Pandas Dataframe with multiple conditions

In [42]:
# assign data
df = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

In [43]:
#  filter dataframe
display(df.loc[(df['Salary']>=100000) & (df['Age']< 40) & (df['JOB'].str.startswith('D')),
                    ['Name','JOB']])

        Name       JOB
0   RACHEL    DESIGNER

In [56]:
# filter with numpy 
Values = np.where((df['Salary']>=100000) & (df['Age']< 50) & (df['JOB'].str.startswith('D')) )
print(Values)
display(df.loc[Values])

(array([0]),)

        Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

In [57]:
# Filter Pandas Dataframe Using Query (eval and query works only with columns)


display(df.query('Salary  <= 100000 & Age < 40 & JOB.str.startswith("C").values'))

        Name  Age  Salary   JOB
1   MONICA     35   93000  CHEF

##  Pandas Merging, Joining and Concatenating